### ISSUE TITLE
Uncaught Error: Cannot find module 'poor-mans-t-sql-formatter'

### ISSUE THREAD

**Issue by irnc** [TaoK/poor-mans-t-sql-formatter-atom-package#5]
1. Click on Install from Settings > Install.

**Atom**: 1.23.1 x64
**Electron**: 1.6.15
**OS**: Mac OS X 10.13.2
**Thrown From**: [poor-mans-t-sql-formatter](https://github.com/TaoK/poor-mans-t-sql-formatter-atom-package) package 1.6.10

### Stack Trace

Uncaught Error: Cannot find module 'poor-mans-t-sql-formatter'

```
At /Applications/Atom.app/Contents/Resources/app/static/<embedded>:1

Error: Cannot find module 'poor-mans-t-sql-formatter'
    at Module._resolveFilename (module.js:470:15)
    at Module._resolveFilename (/Applications/Atom.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app/src/module-cache.js:354:58)
    at Module.require (/app.asar/static/index.js:40:43)
    at require (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:66:33)
    at /packages/poor-mans-t-sql-formatter/lib/main.js:7:30)
    at /packages/poor-mans-t-sql-formatter/lib/main.js:120:2)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (internal/module.js:20:19)
    at customRequire (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:96:26)
    at Package.module.exports.Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app/src/package.js:937:35)
    at Package.module.exports.Package.activateConfig (/Applications/Atom.app/Contents/Resources/app/src/package.js:303:18)
    at PackageManager.module.exports.PackageManager.packageHasSettings (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-manager.js:68:20)
    at PackageCard.hasSettings (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-card.js:793:40)
    at PackageCard.updateSettingsState (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-card.js:438:22)
    at PackageCard.updateInterfaceState (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-card.js:430:18)
    at /Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-card.js:727:22
    at /Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-card.js:810:17
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at PackageManager.module.exports.PackageManager.emitPackageEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-manager.js:703:33)
    at /Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-manager.js:542:32
    at exit (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-manager.js:128:22)
    at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:338:17)
    at ChildProcess.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:368:17)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
```

### Commands

```
     -0:32.2.0 settings-view:open (input.hidden-input)
     -0:28.5.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
atom-ide-ui 0.7.0 
editorconfig 2.2.2 
ide-typescript 0.7.2 
language-csv 1.1.2 
linter-eslint 8.4.0 
node-debugger 1.10.1 
poor-mans-t-sql-formatter 1.6.10 
pretty-json 1.6.4 
tablr 1.8.3 
teletype 0.4.0 
```

**Comment by TaoK** [comment]
Well that sucks. Sorry I didn't see this until today :( 

No idea what's going on, will take a look at some point over the next few days.

**Comment by databasekevin** [comment]
Got the same thing which is too bad because Atom really needs a way to format SQL easily. :(

**Comment by databasekevin** [comment]
Any chance this is still going to be corrected? NP++ is now crap with the new plugin admin that prevents poor-mans-t-sql from being used - would really love to be able to use on Atom.

**Comment by TaoK** [comment]
Hi, sorry about the silence here, I think I missed this issue. I might get a chance to look at this soon, it looks like it should be trivial, I had it working when I published, not long before this issue was created.

In the meantime, NP++ should have the poor man's t-sql formatter available in plugin admin as of next version (7.6.3 I guess), and VS Code already has it working and available.

**Comment by TaoK** [comment]
Hah, just read my own comment above. Shouldn't do this on a mobile phone, I just betray the sieve-like nature of my memory.

**Comment by TaoK** [comment]
This is now fixed. For the record, this was a workflow bug: Atom's package publishing system, apm, takes the contents of the folder you run it in as-is, and I had updated the package dependency (poor man's t-sql formatter library version 1.6.10) but not actually run npm install... so the reference was correct, but **the files were missing**.

I'll try to keep this in mind next time, and at a minimum, test...
