### ISSUE TITLE
Failed to activate the poor-mans-t-sql-formatter package

### ISSUE THREAD

**Issue by ghost** [TaoK/poor-mans-t-sql-formatter-atom-package#6]
[Enter steps to reproduce:]

1. right-click on file editor 
2. choose format-sql (or something like this, I've uninstalled this plugin...)

**Atom**: 1.25.0 x64
**Electron**: 1.7.11
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [poor-mans-t-sql-formatter](https://github.com/TaoK/poor-mans-t-sql-formatter-atom-package) package 1.6.10

### Stack Trace

Failed to activate the poor-mans-t-sql-formatter package

```
At Cannot find module 'poor-mans-t-sql-formatter'

Error: Cannot find module 'poor-mans-t-sql-formatter'
    at Module._resolveFilename (module.js:470:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.25.0/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.25.0/resources/app/src/module-cache.js:354:58)
    at Module.require (/app.asar/static/index.js:40:43)
    at require (~/AppData/Local/atom/app-1.25.0/resources/app/src/native-compile-cache.js:66:33)
    at /packages/poor-mans-t-sql-formatter/lib/main.js:7:30)
    at /packages/poor-mans-t-sql-formatter/lib/main.js:120:2)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.25.0/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.25.0/resources/app/src/compile-cache.js:240:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (internal/module.js:20:19)
    at customRequire (~/AppData/Local/atom/app-1.25.0/resources/app/static/<embedded>:96:26)
    at Package.requireMainModule (~/AppData/Local/atom/app-1.25.0/resources/app/src/package.js:782:33)
    at Package.activateNow (~/AppData/Local/atom/app-1.25.0/resources/app/src/package.js:220:40)
    at activationCommandSubscriptions.add.commandRegistry.onWillDispatch.event (~/AppData/Local/atom/app-1.25.0/resources/app/src/package.js:865:28)
    at Function.module.exports.Emitter.simpleDispatch (~/AppData/Local/atom/app-1.25.0/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (~/AppData/Local/atom/app-1.25.0/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.25.0/resources/app/src/command-registry.js:360:24)
    at CommandRegistry.dispatch (~/AppData/Local/atom/app-1.25.0/resources/app/src/command-registry.js:273:23)
    at AtomEnvironment.dispatchContextMenuCommand (~/AppData/Local/atom/app-1.25.0/resources/app/src/atom-environment.js:1347:25)
    at EventEmitter.outerCallback (~/AppData/Local/atom/app-1.25.0/resources/app/src/application-delegate.js:346:53)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:197:7)
```

### Commands

```
     -0:26.7.0 intentions:highlight (input.hidden-input)
     -0:26.2.0 application:new-file (input.hidden-input)
     -0:26 core:paste (input.hidden-input)
     -0:19.8.0 grammar-selector:show (atom-text-editor.editor.is-focused)
     -0:18 core:confirm (input.hidden-input)
     -0:10.5.0 poor-mans-t-sql-formatter:format (div.line)
```

### Non-Core Packages

```
atom-clock 0.1.16 
atom-ide-ui 0.9.4 
block-comment 0.4.3 
busy-signal 1.4.3 
formatter 2.12.4 
ide-rust 0.15.1 
ide-typescript 0.7.6 
intentions 1.1.5 
language-rust 0.4.12 
linter 2.2.0 
linter-rust 0.8.4 
linter-ui-default 1.7.1 
nuclide-format-js 0.0.45 
pdf-view 0.66.0 
poor-mans-t-sql-formatter 1.6.10 
script 3.17.3 
teletype 0.10.0 
unicode-input 0.5.1 
xml-formatter 0.11.0 
```

**Comment by TaoK** [comment]
Hi, this is finally resolved - my apologies for the delay, this issue clearly slipped by me. It might help explain why poor man's t-sql formatter has been so unpopular on Atom compared to VS Code, Notapad++, etc - no-one's been able to use it for over a year...
